name = "unjs"
type = "javascript"
account_id = "8ea39dfb7bb411de7fcff5444d7a5dbb"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-03-06"

[site]
bucket = "./.output/public"
entry-point = "./.output"
