name: cloudflare

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - run: pnpm install
      - name: Build
        run: pnpm build
        env:
          NITRO_PRESET: cloudflare
      - name: Publish to cloudflare
        uses: cloudflare/wrangler-action@3.0.1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
