name: Update Packages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1' # Every monday at 7am UTC

permissions:
  pull-requests: write
  contents: write

jobs:
  update-packages:
    if: github.repository_owner == 'unjs'
    name: Update Packages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 0
      - run: corepack enable
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - run: pnpm run cli github sync-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
